/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conversion_numeros;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

/**
 *
 * @author pedro
 */
public class ventana extends javax.swing.JFrame {

    /**
     * Creates new form ventana
     */
    public ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jrbBinario = new javax.swing.JRadioButton();
        jrbOctal = new javax.swing.JRadioButton();
        jrbDeciamal = new javax.swing.JRadioButton();
        jrbHexadeciamal = new javax.swing.JRadioButton();
        binario = new javax.swing.JTextField();
        octal = new javax.swing.JTextField();
        decimal = new javax.swing.JTextField();
        hexadecimal = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(jrbBinario);
        jrbBinario.setText("Binario");
        jrbBinario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        buttonGroup1.add(jrbOctal);
        jrbOctal.setText("Octal");

        buttonGroup1.add(jrbDeciamal);
        jrbDeciamal.setText("Decimal");

        buttonGroup1.add(jrbHexadeciamal);
        jrbHexadeciamal.setText("Hexadecimal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbBinario)
                    .addComponent(jrbOctal)
                    .addComponent(jrbDeciamal)
                    .addComponent(jrbHexadeciamal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jrbBinario)
                .addGap(29, 29, 29)
                .addComponent(jrbOctal)
                .addGap(29, 29, 29)
                .addComponent(jrbDeciamal)
                .addGap(33, 33, 33)
                .addComponent(jrbHexadeciamal)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        binario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                binarioKeyTyped(evt);
            }
        });

        octal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                octalKeyTyped(evt);
            }
        });

        decimal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                decimalKeyTyped(evt);
            }
        });

        hexadecimal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hexadecimalKeyTyped(evt);
            }
        });

        jButton1.setText("Convertir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Nava");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(67, 67, 67)
                                .addComponent(jButton2)
                                .addGap(80, 80, 80)
                                .addComponent(jButton3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(binario)
                                    .addComponent(octal)
                                    .addComponent(decimal)
                                    .addComponent(hexadecimal, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1)))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(binario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(octal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(decimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(hexadecimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //boton de convertir
        if (jrbBinario.isSelected()) {
            String texto;
            texto = binario.getText();
            octal.setText(bin_oct(texto));
            decimal.setText(bin_dec(texto));
            hexadecimal.setText(bin_hex(texto));
        }

        if (jrbOctal.isSelected()) {
            String texto;
            texto = octal.getText();
            binario.setText(oct_bin(texto));
            decimal.setText(oct_dec(texto));
            hexadecimal.setText(oct_hex(texto));
        }

        if (jrbDeciamal.isSelected()) {
            String texto;
            texto = decimal.getText();
            binario.setText(dec_bin(texto));
            octal.setText(dec_oct(texto));
            hexadecimal.setText(dec_hex(texto));
        }

        if (jrbHexadeciamal.isSelected()) {
            String texto;
            texto = hexadecimal.getText();
            binario.setText(hex_bin(texto));
            octal.setText(hex_oct(texto));
            decimal.setText(hex_dec(texto));
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        // TODO add your handling code here:
        binario.setText("");
        octal.setText("");
        octal.setText("");
        hexadecimal.setText("");
       decimal.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void binarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_binarioKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((c != '0') && (c != '1')) {
            evt.consume();
        }
    }//GEN-LAST:event_binarioKeyTyped

    private void decimalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_decimalKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }

    }//GEN-LAST:event_decimalKeyTyped

    private void hexadecimalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hexadecimalKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != 'A' && c != 'B' && c != 'C' && c != 'D' && c != 'E' && c != 'F') {
            evt.consume();
        }
    }//GEN-LAST:event_hexadecimalKeyTyped

    private void octalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_octalKeyTyped
        char c = evt.getKeyChar();
        if (c != '0' && c != '1' && c != '2' && c != '3' && c != '4' && c != '5' && c != '6' && c != '7') {
            evt.consume();
        }
    }//GEN-LAST:event_octalKeyTyped

    String dec_bin(String valor) {
        int dec = Integer.parseInt(valor);
        valor = Integer.toBinaryString(dec);
        return valor;
    }

    String dec_hex(String valor) {
        int dec = Integer.parseInt(valor);
        valor = Integer.toHexString(dec);
        return valor;
    }

    String dec_oct(String valor) {
        int dec = Integer.parseInt(valor);
        valor = Integer.toOctalString(dec);
        return valor;
    }

    String bin_dec(String valor) {
        int dec = Integer.parseInt(valor, 2);
        valor = Integer.toString(dec);
        return valor;
    }

    String bin_hex(String valor) {
        int dec = Integer.parseInt(valor, 2);
        valor = Integer.toHexString(dec);
        return valor;
    }

    String bin_oct(String valor) {
        int dec = Integer.parseInt(valor, 2);
        valor = Integer.toOctalString(dec);
        return valor;
    }

    String hex_dec(String valor) {
        int dec = Integer.parseInt(valor, 16);
        valor = Integer.toString(dec);
        return valor;
    }

    String hex_bin(String valor) {
        long dec = Integer.parseInt(valor, 16);
        valor = Long.toBinaryString(dec);
        return valor;
    }

    String hex_oct(String valor) {
        int dec = Integer.parseInt(valor, 16);
        valor = Integer.toOctalString(dec);
        return valor;
    }

    String oct_dec(String valor) {
        int dec = Integer.parseInt(valor, 8);
        valor = Integer.toString(dec);
        return valor;
    }

    String oct_bin(String valor) {
        int dec = Integer.parseInt(valor, 8);
        valor = Integer.toBinaryString(dec);
        return valor;
    }

    String oct_hex(String valor) {
        int dec = Integer.parseInt(valor, 8);
        valor = Integer.toHexString(dec);
        return valor;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField binario;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField decimal;
    private javax.swing.JTextField hexadecimal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jrbBinario;
    private javax.swing.JRadioButton jrbDeciamal;
    private javax.swing.JRadioButton jrbHexadeciamal;
    private javax.swing.JRadioButton jrbOctal;
    private javax.swing.JTextField octal;
    // End of variables declaration//GEN-END:variables
}
